empresa:
    type: rest
    resource: App\AppBundle\Controller\EmpresaController

cliente:
    type: rest
    resource: App\AppBundle\Controller\ClienteController

venda:
    type: rest
    resource: App\AppBundle\Controller\VendaController
